### ISSUE TITLE
Rhino 6 - Message: cannot import convex_hull_numpy from compas.geometry

### ISSUE THREAD

**Issue by yck011522** [BlockResearchGroup/compas_assembly#2]
**Describe the bug**
I made a fresh install of compas and compas_assembly using Anaconda Prompt (Admin Mode)

```
conda create -n compas_assembly python=3.7 COMPAS shapely
conda actiavte compas_assembly
pip install git+https://github.com/BlockResearchGroup/compas_assembly.git

python -m compas_rhino.install -v 6.0
python -m compas_rhino.install -p compas_assembly
```

To verify it, I go into python (Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)] :: Anaconda, Inc. on win32). Type in the following line:

`from compas_assembly.datastructures import Assembly`

No error.

However, when using the same line from Rhino,  the following error appeared:

`Message: cannot import convex_hull_numpy from compas.geometry`

**To Reproduce**
1. Win 10 64bit. Rhino 6 SR16
2. Sample script
3. Sample data

Message: cannot import convex_hull_numpy from compas.geometry

Traceback:
  line 5, in <module>, "C:\Users\leungp\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\compas_assembly\datastructures\hull_numpy.py"
  line 60, in <module>, "C:\Users\leungp\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\compas_assembly\datastructures\__init__.py"
  line 18, in <module>, "G:\01_Projekte\270_PhD_SpatialTimberStructures\03_Design\20190716 YiJiang Integration\TestScript.py"

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**
 - Python version [e.g. 2.7]
 - Python package manager [e.g. macports, pip, conda]

**Additional context**

**Comment by tomvanmele** [comment]
yes that makes sense. there have been some changes in the way `compas` makes `numpy`-dependent functionality available and that triggered an error when importing `convex_hull_numpy` in Rhino. try updating `compas_assembly` to `0.1.8` and let me know what happens.

**Comment by tomvanmele** [comment]
have done a few more updates. latest version is `0.2.1`...

**Comment by yck011522** [comment]
Hi Tom, Thanks for the speedy update. Now it all works.
